<?php
/**
 * Created by PhpStorm.
 * User: 伍先生
 * QQ  : 3383600886
 * Date: 2019/9/4
 * Time: 22:01
 * Info: 说明
 */

namespace app\jwcode\controller;


use think\Controller;

class Web extends Controller
{
    public function __construct()
    {
        parent::__construct();
        header("Access-Control-Allow-Origin:*");//*星号表示所有的域都可以接受
        header("Access-Control-Allow-Methods:GET,POST");
        header('Access-Control-Allow-Headers:x-requested-with,content-type');
    }

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        //系统信息
        $data = db('System')->where('title','seo')->value('json');
        $data = json_decode($data,1);


        $this->assign("seo",$data);
    }


}